# Children's Comprehension of Disjunction {#devoLit}

## Introduction

The previous chapters focused on disjunction in child-directed speech, but most of the developmental research on disjunction has concentrated on experimental studies that test children's comprehension. This chapter provides a summary of these studies. They divide roughly into two periods. First, in the late 1950s and early 1960s, many psychologists were conducting research on children's development of logical reasoning kicked off by @piaget1958growth. Even though this line of research started by investigating the interpretation of linguistic connectives such as *and* and *or*, the main interest was the development of logical concepts and later investigations focused on non-linguistic logical reasoning. Second, in late 90s and early 2000s, a separate line of research inspired by advances in formal semantics/pragmatics started which focused more on the development of the words *and*/*or* and aimed at capturing children's semantic and pragmatic competence.

With respect to children's comprehension of *or*, these two research programs diverge both empirically and theoretically. Empirically, the early research on logical reasoning suggested that children first learn the exclusive interpretation of *or* ($\oplus$), and only later do they develop the understanding of inclusive (often called logical) disjunction. Furthermore, the research suggested that sometimes children (and even teenagers) interpret *or* like a conjunction. On the contrary, later research on semantic acquisition suggested that children learn the inclusive interpretation before the exclusive one. The existence of conjunctive interpretations was denied for a long time but it has resurfaced recently [@Singh2016]. Theoretically, the research on logical reasoning considered logical thinking as an abstract kind of thinking that is present only in late stages of development. The research in semantic acquisition considers logical concepts present early in development and some researchers even consider them innate.

These two research programs also diverge in their assumptions with respect to the learning process. Similar to many other areas of developmental research, the present accounts of children's acquisition of disjunction fall either closer to the nature side or the nurture side of the nativist-empiricist debate. In fact, the interpretation of *or* has become a stronghold for nativist theories of language acquisition in the past decade [@crain2008logic]. The empiricists have not been as unified and vocal but it is possible to see them represented by the early work on logical reasoning as well as a usage-based approach advocated by @morris2008logically. 

The nativist and usage-based positions differ on almost every major acquisition issue: the nature of the input data (poverty vs. richness), the cognitive mechanisms applied to the data (domain specific vs. domain general), and the nature of linguistic knowledge (abstract generative model vs. constructions and generalizations). In the nativist account, linguistic knowledge is the result of the triggering effect of the poor and noisy input data on innate linguistic (hence domain specific) principles and parameters. The common metaphor is that of maturation, from an initial state of the language faculty to a final stage. In the usage-based approach, linguistic knowledge is the result of applying general purpose cognitive mechanisms and principles to the input linguistic data. The input data is rich and plays a major role in children's acquisition of language. Frequency in the input is an important component of the usage based theory's predictions on the acquisition pattern. More frequent constructions are predicted to be acquired earlier and faster. 

The debate on children's acquisition of logical connectives mirrors this overarching nature-nurture debate. The nativist literature emphasizes the poverty of the stimulus and posits innate logical principles and parameters. The usage-based approach emphasizes the richness of the input and the predictive power of child-direct speech on children's linguistic productions. In the next three subsections, I go over the existing literature on children's acquisition of logical connectives. I start with the research program on children's development of logical reasoning. Then I discuss the usage-based approach to the acquisition of logical connectives which can be considered as the true heir of the research on logical reasoning. In the third subsection, I discuss the literature on semantic/pragmatic acquisition, specifically the logical nativist position that stands in contrast to the first two.

##The Development of Logical Reasoning

###Theoretical Landscape

Investigations on children and adults' comprehension of logical words such as *or* started in the 60s with the work of @nitta1966basic on Japanese and @neimarkSlotnick1970 on English, and continued until mid 80s. These studies focused mainly on children's conceptual development and more specifically, children's development of logical reasoning. The theoretical paradigm behind them was Piaget's theory of cognitive development. There were four main stages of development in Piaget's theory: sensorimotor stage (ages 0-2;0), pre-operational stage (ages 2-7 years), concrete operational stage (ages 7-11 years), and formal operational stage (11 years and above). The operational stages (concrete and formal) were considered the period where children develop logical thinking [@piaget1958growth]. The idea was that children start applying logical thinking or abstract mental operations (rule-based thinking) around the age of 7. At first, they can only apply logical thinking to concrete objects (concrete operational stage) but later when they are about 11, they learn logical reasoning in an abstract and hypothetical fashion. As a result, the majority of research on children's understanding of logical connectives in this period focused on children and adolescents between the ages of 6 and 18. 

Early studies such as @neimarkSlotnick1970 reported findings that presumably supported the Piagetian theory. For example, they found that the meaning of *or* is not understood until late in the period of formal operations [@neimark1970]. Later research such as @johansson1975preschool and @braine1981development showed that the development of children's connective comprehension does not fully match the stages of the Piagetian theory. However, the idea that a full mastery of the "logical" (inclusive) meaning of *or* is acquired later survived and was inherited by the usage-based approach. The main idea was that children's initial conceptualization/interpretation of disjunction is simply a "choice" between two options (exclusive) and only later do they learn the logical and inclusive meaning of *or*. These approaches predicted that the exclusive interpretation emerges before the inclusive interpretation in child language.

###Empirical Landscape

Studies on the development and comprehension of logical connectives were kicked off by @nitta1966basic. They tested 679 Japanese children in grades K, 2, 4, 6, and 8. Children were tested on negation, conjunction, and disjunction. Each question provided six alternatives to circle, for example a fish, a bird, and a flower, each with a white and a black version. Participants were asked to circle all items described by statements such as: "flower", "not bird", "bird and flower", "bird or flower", "black and bird", "black or flower", etc. The researchers reported that all children understood the negation of a statement well. Conjunction was understood by older children better than younger ones. With disjunction, however, even older children struggled to interpret the statements correctly. @neimarkSlotnick1970 replicated these findings in English. They tested 455 children in grades 3-8 and 58 college students. They concluded that the majority of the participants understood negation and conjunction, but only college students correctly answered statements with disjunction. 

Table \@ref(tab:NeimarkTable) reports the percentages of correct responses in @neimarkSlotnick1970. They reported that participants made two types of errors. First across all ages, some participants interpreted disjunction as conjunction. For example they circled black birds when the instruction said "black or bird". Second, some selected only one of the two categories. For example, they selected only birds in "black or bird". They also tested participants on disjunctions like "A, B, or both". In table \@ref(tab:NeimarkTable), the incorrect responses for a statement like "A or B" could be due to exclusive or conjunctive interpretations, but the incorrect responses for a statement such as "A or B, or both" were probably due to conjunctive interpretations. Based on these results @neimark1970 concluded that a correct undersanding of disjunction is only developed in high school years and depends on the attainment of formal operations as stated in the Piagetian theory.

|Construction|KJ|2J|3G|4G|4J|5G|6G|6H|6J|7C|7H|8C|8H|8J|9C|Col|
|--------------|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|
|A and B|92|84|35|50|92|50|41|54|98|60|67|61|68|100|65|93|
|A or B|2|9|15|8|22|19|23|31|59|45|38|39|28|49|55|97|
|A, B, or Both|15|20|12|29|49|31|14|50|82|60|62|48|52|88|60|97|
Table: (\#tab:NeimarkTable) Percentage of correct responses to statemetns with conjunction and disjunction on the picture selection task in @nitta1966basic and @neimarkSlotnick1970 as reported in @neimarkSlotnick1970. Abbreviations: J=Japanese, G= Grandview Elementary Highschool, H=Highland Park Middle School, C=Conackamack Junior High School, Col = Douglass College.

@paris1973comprehension used a similar in-classroom setup to test children's comprehension of connectives in Grades 2, 5, 8, 11, and college. 200 participants (40 per grade) were asked to judge the truth of sentences with connectives such as *and*, *or*, and *either-or*. The experimenter showed participants slides of pictures, for example a bird in a nest, with descriptions such as "the bird is in the nest or the shoe is on the foot." The participants were asked to judge the statement as true or false. Paris found that statements with *and* were almost always judged as expected and correctly. This was not the case with disjunction. 

Table \@ref(tab:ParisTable) summarizes the percentage of errors for disjunctive statements. The results show two trends. First, older participants produce more errors when both disjuncts were true (A=T, B=T). This suggests that older participants were more likely to interpret a disjunction as exclusive. Second, the majority of younger children, and even around a fifth of college students considered a disjunction false when only one of the disjuncts was true (A=T,B=F or A=F,B=T). The combination of these two trends suggested that initinally, children do not differentiate *or* from *and*, interpreting both as conjunction. Finally, Paris also found that there were fewer errors with the *either-or* statements compared to the *or* statements. He suggested that the word *either* could provide further cue on how disjunction should be interpreted.

@paris1973comprehension attributed the conjunctive interpretations of *or* to children applying non-linguistic strategies when an utterance is hard to interpret [See @clark1973non for a discussion of nonlinguistic strategies in child language acquisition]. He suggested that children in his task were "comparing visual and auditory information with little regard for the implied logical relationship in the verbal description." In other words, children responded with "true" if the individual disjuncts matched the pictures and false otherwise. Such a non-linguistic strategy would yield correct answers for conjunction but incorrect (conjunctive) answers for disjunction. This explains why conjunctive readings reduce with age and why using the word *either* helps reducing conjunctive interpretations further.

|Construction|Truth Values|2|5|8|11|C|
|---------------|--------------------|----|----|----|----|----|
|A or B|A=T, B=T|2.5|22.5|15|25|25|
|A or B|A=T, B=F|67.5|70|50|30|27|
|A or B|A=F, B=T|72.5|62.5|47.5|27.5|20|
|A or B|A=F, B=F|2.5|2.5|2.5|0|0|
|Either A or B|A=T, B=T|7.5|25|25|27.5|32.5|23.5|
|Either A or B|A=T, B=F|50|57.5|35|10|12.5|
|Either A or B|A=F, B=T|62.5|45|37.5|10|10|
|Either A or B|A=F, B=F|5|17.5|10|0|0|
Table: (\#tab:ParisTable) Percentage of errors to statements with disjunction in @paris1973comprehension.

@suppes1969young was the first study to investigate children's understanding of connectives in an experimental setting rather than an in-class test. The study had 64 children between the ages of 4.5 and 6.5 years and used 18 wooden blocks with different shapes (star, circle, square) and colors (red, green, black). The experimenter asked children to give her the blocks using 12 different imperative sentences. The sentences with *and*/*or* in Study 1 and 2 are listed in Tables \@ref(tab:suppesFeldmanOne) and \@ref(tab:suppesFeldmanTwo). The responses were coded based on the objects handed to the experimenter. Consider a command such as "give me the things that are green or square!" An "intersection" response was coded when the child gave the experimenter all green squares. With a "union" response, the child gave the experimenter all green objects and all square objects. Finally, an "only one" response was coded when children gave the experimenter all objects that had only one of the properties, for example all green objects. "Other" includes all other types of responses. The results showed two patterns of interpretation for *or*. First, interpreting it as *and* which often resulted in an "intersection" response. Second, interpreting *or* as exclusive disjunction which resulted in an "only one" response. @suppes1969young were probably the first to show that preschool children can interpret *or* as exclusive disjunction in imperative sentences.

|Command| Intersection | Union | Only One | Other |
|-----------------------------------|----|----|----|----|
|Give me the red things and the square things! | 11 | 33 | 33 | 23 |
|Give me all the things that are black and square! | 42 | 13 | 33 | 12 |
|Give me the green things, or, the round things! | 9 | 6 | 68 | 17 |
|Give me the things that are green or square! | 47 | 3 | 31 | 19 |
Table: (\#tab:suppesFeldmanOne) Percentages of responses to the statements with *and*/*or* in Study 1 of @suppes1969young.

|Command| Intersection | Union | Only One | Other |
|---------------------------------------|----|----|----|----|
|Give me the things that are red and square! | 42 | 10 | 12 | 36 |
|Give me the round and black things! | 34 | 10 | 22 | 32 |
|Give me the black things and the square things! | 21 | 14 | 33 | 32 |
|Give me the things that are round or green! | 30 | 7 | 24 | 39 |
|Give me the red or star things! | 34 | 6 | 36 | 24 |
|Give me the stars or the green things! | 21 | 6 | 34 | 39 |
Table: (\#tab:suppesFeldmanTwo) Percentages of responses to the statements with *and*/*or* in Study 2 of @suppes1969young.

@johansson1975preschool provided further evidence that young children often interpret a disjunction as exclusive in imperative sentences.They investgiated 60 2-to-7-year-old Swedish-speaking children on their interpretation of the words *and*/*or*. They used a felt board and 8 pictures of toys, clothes, food, furniture, and tools. In one of their tasks, they provided children with 4 pictures and asked them to put some pictures on the felt board. The commands included the words *and*/*or*, for example, "put up the doll and the dog" or "put up the car or the bicycle". The study found that more than 80% of the children who were four-years-old and older interpreted *and* correctly and put both pictures on the board, while most younger children simply put all the four available pictures on the board. With *or*, most four-year-olds and older children put only one of the mentioned pictures on the board which suggested an exclusive interpretation. Similar to *and*, most younger participants put all the available pictures on the board. In another task, the connectives were placed in a declarative sentence such as "Richard wants to drink lemonade or milk" and the experimenter asked the children to use the pictures to show what Richard drank. The study found similar results to the previous task. @johansson1977levels used an in-class test similar to @neimarkSlotnick1970 but adopted the commands in @suppes1969young. He showed that children older than 6 years as well as college students often interpet *or* as exclusive in commands like "circle all figures that are blue, or, all that are square."

Finally, @braine1981development tested children and adults on both commands and judging truth value of statements with *or*. They had 22 children in each four age groups of 5-6, 7-8, 9-10, and college students. In one task, they used the same paradigm as @suppes1969young and asked the children to give them wooden blocks. They used commands such as "give me all the green things or give me all the round things". Table \@ref(tab:brainRumainTableOne) summarizes the findings. They found that the vast majority of participants in all age groups interpreted *or* as exclusive disjunction in this task. 

In a second task, @braine1981development asked participants to judge the truth value of a puppet's statement about four boxes. Each box had several animals in it and the content was visible to children but not the puppet. The puppet would look into each box and say statements such as "either there's a duck or a horse in the box." The boxes represented the four possible truth values with respect to each proposition: TT, TF, FT, and FF. The experimenter asked children if the puppet's statement was right. Table \@ref(tab:brainRumainTableTwo) summarizes the findings of this task and categorizes the responses for each box as a string of yes's and no's. The younger participants showed more conjunctive and inclusive interpretations while older participants, especially college students, showed inclusive and exclusive interpretations. 

Given that the same participants took both tasks, @braine1981development show that the task design can affect our conclusions on how participant's interpret a disjunction. In the first task where experimenters used commands to ask for objects, participants appeared to interpret *or* as exclusive disjunction. However, the same participants showed inclusive and conjunctive interpretations in a task where they were asked to judge the statement of a puppet as "right" or "wrong". Since the tasks differed in their linguisic stimuli as well as the non-linguistic aspects of the task, it is not clear how much of the difference between the tasks is due to the difference in the speech acts used, namely commands vs. statements.

|Command| 5-6 | 7-8 | 9-10 | Adults |
|----------------------------------|----|----|----|----|
|Give me all the green things or give me all the red things! | 86 | 91 | 86 | 91 |
|Give me all those things that are either blue or round! | 95 | 86 | 82 | 73 |
Table: (\#tab:brainRumainTableOne) Percentages of exclusive responses to the commands in Study 1 of @braine1981development

|Command| 5-6 | 7-8 | 9-10 | Adults |
|---------------|----|----|----|----|
|YYYN (Inclusive) | 18 | 41 | 50 | 32 |
|NYYN (Exclusive) | 0 | 14 | 9 | 41 |
|YNNN (Conjunctive) | 32 | 14 | 14 | 9 |
|YPPN | 41 | 19 | 14 | 9 |
|Other| 10 | 14 | 14 | 9 |
Table: (\#tab:brainRumainTableTwo) Percentages of response categories to the statements in Study 3 of @braine1981development. Y= Yes, N= No, P= Partly right. Category "other" includes YYNN, and NNNN.

Table \@ref(tab:piagetable) summarizes the 7 studies discussed in this section. The major take-away from these studies was that the interpretation of disjunction depends on the age of the participants and the task used. Younger participants interpreted *or* as exclusive disjunction or conjunction. Conjunctive interpretations were explained as the application of a non-linguistic strategy when the meaning of *or* was not known or the task was too demanding/confusing. Older participants and adults interpreted *or* often as exclusive disjunction, and sometimes as inclusive disjunction. The concensus was that the inclusive (often called "logical") interpretation of a disjunction develops in high school years. 

Studies in this period also found that a correct interpretation of *and* develops earlier than *or*. They connected this finding to the literature on disjunctive and conjunctive rule learning. Some studies had discovered that conjunctive rules are easier to detect and learn than disjunctive ones [@neisser1962hierarchies]. However, most authors also acknowledged the role of language and suspected that *or* gives rise to a wider range of interpretations, and this can delay its acquisition. @frenchNelson1985 suggested that *or* is less frequent in children's input and discussed frequency as another factor that can cause a delay in children's acquisitoin of linguistic disjunction.

| Study | Age | $n$ | Language | Environment | Interpretation |
|---------------|:-----:|:-----:|-----|:--------------------------:|:--------:|
|@nitta1966basic | K, G2,4,6,8 | 679 | Japanese | Imperatives, Universal (Nuclear Scope) |$\oplus$, $\land$|
|@neimarkSlotnick1970 | 3-9G, C | | English | Imperatives, *all* (Nuclear Scope) | $\oplus$, $\land$|
|@suppes1969young | 4;5-6;7 | 64 | English | Imperatives, *all* (Nuclear Scope)| $\oplus$, $\land$|
|@paris1973comprehension | G2,5,8,11, C | 200 | English | Present Declarative | $\oplus$, $\land$|
|@johansson1975preschool | 2;0-7;6 | 60 | Swedish | Present Declarative |$\oplus$|
| |  |  | | Imperative |$\oplus$|
|@johansson1977levels | 6-10, 12, 22 | 70 | Swedish | Imperative | $\oplus$|
| | | | | Imperative, *all* restrictor | $\oplus$|
@braine1981development | 5-10, C | 88 | English | Imperative, *all* (Restriction) | $\oplus$|
 | | | | |Present Declarative | $\land$, $\lor$, ($\oplus$ for C)|
Table: (\#tab:piagetable) Summary of some studies on children's interpretation of the disjunction word in the literature on children's cognitive development. K is short for kindergarten, G for grade, and C for college.

##The Usage Based Approach

Usage-based researchers have not been active in children's acquisition of logical words. There is only one paper by @morris2008logically that investigates children's acquisition of *and* and *or* by conducting a corpus study. Here I summarize the assumptions, claims, and hypotheses of this paper and more generally the usage based approach to the acquisition of meaning.

###Theoertical Landscape

The usage-based theory contends that "meaning is use" and "structure emerges from use" [@tomasello2009usage]. Therefore communication is viewed as raison d'etre of language and it is used as an explanatory factor either in the study of adult language or children's acquisition of it. Most importantly, linguistic structure is viewed as a phenomenon emergent from communicative principles and conventions, and domain general cognitive mechanisms recruited to achieve communicative goals. In stark contrast to the nativist theories, the usage-based theory of language acquisition emphasizes children's reliance on their linguistic input. They consider the language children hear around them, especially child-directed speech, as the main source of their linguistic knowledge. Under the usage-based approach, children's input language is a rich source of linguistic information for domain general cognitive mechanisms to analyze and learn their structure. Therefore, children's early language closely matches what they hear around them.

The usage-based approach contends that children's acquisition of language is item-based. Children acquire words and word uses (meanings) item by item and in an isolated fashion. Later they form generalizations over these isolated items and extract abstract information and use a word to convey a broader range of meanings [@lieven1997lexically; @akhtar1999acquiring]. In the usage based theory, meaning is represented as a usage protocol. In usage-based acquisition of meaning children form representations for use based on input from their natural language environments, which may best be described as a conceptual prototype associated with a usage script [@levy1994words; @tomasello2003constructing].

One hypothesis regarding the development of meaning in this framework is the confirmed core-meaning hypothesis:

> "The initial meaning of a connective should be limited to a single, essential meaning [@macwhinney2002competition]. Through increased attention to the productions of others and more heterogeneous functional contexts, children acquire additional meanings (i.e., logical uses) and rules for appropriate use (i.e., pragmatics), and generalize items to more abstract grammatical structures. This confirmed core should (a) have a prototypical meaning, (b) have the least interference with other meanings, and (c) require the least amount of additional cognitive resources [@macwhinney1989competition]. A prototypical meaning likely covers the core function ascribed to a word. The likely prototypical meaning for *and* is conjunction (denoting the inclusion of two or more objects or phrases in a set) while choice (exclusive-or) is a likely candidate for *or*. These functions may help form the basis of word meanings and aid in their acquisition" [@morris2008logically].

The assumption here is that lexical items have multiple meanings or uses, and logical connectives are not exempt. Both *and* and *or* are considered polysemous. They express a variety of uses (interpretations). *And* has a conjunctive use (e.g. that's a mommy and two dogs.), an explanatory use (e.g. you hit him and that is not OK), a temporal use (e.g. He broke the window and then stole the television.), and an extension use (e.g. And who should this be?). *Or* has an exclusive (choice) use (e.g. You can go the table or to the free play area), an inclusive use (e.g. you can have apples or bananas), and a conditional use (e.g. Stop hitting him or you will have to have a time out!)

The developmental predictions of the usage-based approach is that *and* starts from the core meaning of conjunction and later is associated with other uses such as the temporal interpretation and the causal interpretation. *Or* starts with the core "exclusive" (choice) use but expands into the other uses such as "inclusive" and "conditional". Children start with the exclusive meaning since it is more frequent in the input data and furthermore, it has less interference with the meaning of conjunction. Therefore, the usage-based account of Morris predicts that children learn the exclusive interpretation of disjunction before its inclusive interpretation.

###Empirical Landscape

In order to support the hypotheses mentioned in the previous section, @morris2008logically investigated the use of *and* and *or* in child-directed speech and children's production between the ages of 2;0 and 5;0, using 240 transcriptions of audiotaped exchanges obtained in the CHILDES database. Each connective was analyzed with respect to its frequency, syntactic frame, meaning, and formal/informal use. With respect to frequency, the study found that overall, *and* is approximately 12.8 times more likely to be produced than *or*. There were a total of 6,459 connective uses: *and* was produced 5,994 times whereas *or* was produced 465 times. 

Considering syntactic frames, instances of the connective use were coded as appearing in *statements* or *questions*. The study reported that *and* appeared predominantly in statements (more than 90% of the time) while *or* was extremely common in questions (more than 85% of the time). For the meanings and uses of *and* and *or*, the study reported that for both adults and children, the dominant meanings of *and* and *or* were "conjunction" and "exclusive disjunction", respectively. This was taken to support the confirmed core-meaning hypothesis. There was also a significant increase in the mean number of different uses for *and*/*or*. *And* started with only the core conjunctive meaning at 2;0-2;6 and around the ages 3;0 and 4;0, children expanded it to two different uses on average. At 4;6-5, children were producing three different uses of *and*. The production of *or* started at around 3;0-3;6 with the "exclusive" meaning and expanded to 1.5 uses on average by 4;6-5;0.

However, the account above faces an important issue. The conjunctive *and* and temporal/explanation *and*'s do not have the same syntactic status. The former often conjoins noun phrases while the latter two only conjoin sentences. We can have conjoined nouns phrases in utterances with 3 or 4 words while conjoined sentences require utterances longer than 4 words. How can a two-year-old with an average MLU of 1.5-2.5 words produce the temporal or explanation *and* which require conjoined sentences? It is possible that the increase in the number of word usage can be explained by syntactic development rather than semantic development. The absence of the non-conjunctive uses of *and* in the corpus data may only be a phenomenon in production and not comprehension. Even if children understand the meaning of temporal *and*, if they cannot yet produce conjoined sentences, we are not going to observe such uses in the corpus data. This question cannot be resolved by the corpus evidence alone.

Utterances were also coded as informal or formal. Formal uses of connectives were defined as utterances about truth values or states of affairs. For example, a question like "does the dog have a tennis ball and a hockey puck?" to which the child answered with "No" was coded as formal. This is because the inquiry is about the state of the world. However, "I'd like peanut butter and jelly" was considered informal, presumably because it pertains to wants and desires. The study found that there are rare cases of formal use in parents' and children's speech. This is interpreted as evidence for the developmental claim that the connectives' formal/logical (or truth-conditional) interpretation is acquired later in development and it is not part of the core meaning.

##The Gricean Approach and Logical Nativism

The nativist inquiry started by pointing out that the literature on logical reasoning did not control for the linguistic context of *or*. Inspired by Gricean pragmatics, Stephen Crain and colleagues argued that *or* is often accompanied by an exclusivity implicature. They suggested that to understand children's semantic knowledge of *or*, we need to use it in contexts where the exclusivity implicature does not arise. Since early studies on logical reasoning did not control for exclusivity implicatures, they painted an inaccurate picture in which children understood the meaning of *or* as exclusive disjunction. As we will see in this section, most Gricean and nativist research on disjunction focuses on linguistic contexts which are considered to be "implicature-canceling". The argument is that in such contexts, we get a chance to assess the semantics of *or*, rather than its pragmatics. Furthermore, imperative utterances were abandoned because a disjunctive imperative is complied with, when only one of the disjuncts is carried out. However, participants may only be carrying out one of the tasks because it involves less work. Therefore, imperatives do not differentiate between an inclusive or an exclusive interpretation of disjunction. The next two subsections provide theoretical and empirical summaries of the Gricean and logical nativist account. I should add here that while the nativist account assumes Gricean pragmatics, not all Gricean appraoches to semantic development are nativsit. I discuss those studies at the end of the subsection on the empirical landscape.

### The Theoretical Landscape

Logical nativism supposes that humans are biologically endowed with the tools for logical reasoning. The meanings of logical expressions in natural languages are captured by the semantics of logical operators in classical logic. The semantics of these logical operators along with some logical principles and parameters are hypothesized to be innate. The logical nativist position is extensively argued for in @crain2008interpretation, @crain2012emergence, @crain2008logic, and @crain2010logic. Here I summarize the main claims, assumptions, and hypotheses very briefly. I start with the nativist assumption on language processing in general.

According to the Modularity Matching Model, the human language faculty is modular and operations within the language faculty are hierarchically organized (syntax $\rightarrow$ semantics $\rightarrow$ pragmatics). Operations of the higher level components apply to the output of lower level components. The syntax module may propose several analyses of a string of which only some satisfy the input requirements of the semantics module and create a well-formed logical form. The semantics module may propose more than one logical form for a sentences while only one is deemed felicitous by the pragmatics module. [@crain1998investigations; @crain1999methodology]

The famous aphorism of the modularity matching hypothesis is that "syntax proposes and semantics disposes"; in turn semantics proposes and pragmatics disposes. Let's consider the nativist claim on the meaning of logical words such as *and* and *or* across languages. The claim is that the native speaker knowledge of the meanings of logical expressions in natural languages is captured by the semantics of logical operators in classical logic. For example, the meaning of *or* and similar logical words across languages correspond to $\lor$ (inclusive) and not $\oplus$ (exclusive). Let's call this the "logical meaning". 

The above claim is one that logical nativists share, more or less, with many formal semanticists. Discrepancies between the meanings of logical words in natural languages and the logical operators are often attributed to either pragmatic enrichment or crosslinguistic differences in scope assignment. However, a formal semanticist may argue for the logical meaning claim while remaining agnostic with respect to how logical representations relate to psychological representations. This is not so for logical nativists. Implicit in the arguments of logical nativism is the assumption that the formal (logical) descriptions used in modeling linguistic meaning also have psychological reality. In fact, the logical nativist position is even stronger. The main claim is that "the human genome contains a set of innate logical structures" [@crain2012emergence, p. 76]. This set of logical structures includes at least the semantics of logical operators in classical logic, downward entailment, and two scope parameters. I will investigate the elements of this set in more detail here. 

First it is hypothesized that the meanings of logical operators such as $\lnot, \land, \lor, \exists, \forall$ are part of the biological endowment of human beings. Let's call this hypothesis the "Innateness of Logical Meaning". This hypothesis strictly limits the hypothesis space for the meaning of logical words to only those provided by classical logic. The meaning of *or* is a good example here. While the meaning of $\lor$ is innate, the meaning of $\oplus$ is not. The innateness of logical meaning predicts that children do not assign the (lexical) meaning of $\oplus$ to *or* and similar disjunctive expressions in other languages because the meaning of $\oplus$ is simply not provided to them by the Universal Grammar. This is also offered as an explanation for the claim that languages do not lexicalize the meaning of $\oplus$. In other words, if $\oplus$ is never available to humans for form-meaning mapping, it will never appear in world languages as the meaning of a lexical item. The exclusive interpretations of disjunction are explained as pragmatic enrichments.

At this point, a fair objection to the nativist position is the limitation of classical logic in capturing the meaning of logical expressions such as *most*, *many*, and *few*. There are no operators in classical logic that correspond to the meaning of these expressions and under the current formulation of the nativist position, it is not clear how children may learn them. However, logical nativism can avoid this criticism by assuming that the human logical faculty is not completely modeled by classical logic and several operators provided by UG fall outside its scope. In other words, nativists can argue that classical logic is a good approximation to the human logical faculty in many cases such as the meaning of *every*, *some*, *and*, and *or*.

Moving on to the next hypothesis, @crain2012emergence suggests that the property of downward entailment is also innate. More specifically, he argues that the child is innately instructed that downward entailing environments license Negative Polarity Items (NPIs) and generate a conjunctive reading of *or*. Below, $\Delta$ stands for a downward entailing operator such as negation, the restrictor of *every*, the meaning of *before*, or the antecedent of a conditional [@crain2008interpretation; @crain2012emergence].

> Innateness of Downward Entailment: Downward entailment and the behavior of logical operators in such environments are innate. Example; The conjunctive entailment of disjunction: $\Delta (A \lor B) \Rightarrow \Delta (A) \land \Delta (B)$.

It is not clear why the property of downward entailment needs to be innate. One way to explain this is that downward entailment is a grammatical feature that is not learnable and needs to be part of Universal Grammar. However, on purely semantic grounds, children's awareness of subset-superset relations along with the innateness of logical meaning may predict the DE behavior of operators or NPIs.

Logical nativism also claims that languages vary with respect to their scope taking properties of disjunction and conjunction with negation. Languages like English require disjunction and conjunction to scope under negation while those like Mandarin require disjunction and conjunction to scope above negation. Two scope parameters are proposed to explain this scope variation. One guides the scope of negation and conjunction and the other commands the scope relation of negation and disjunction: 1. [$\lnot > \lor$] vs. [$\lor > \lnot$] 2. [$\land > \lnot$] vs. [$\lnot > \land$]. 

I have written the default value of each parameter on the left. The default value for disjunction is [$\lnot > \lor$] and for conjunction [$\land > \lnot$]. Children speaking any language in the world are expected to start with these default values and if the input data is consistent with the non-default value, then there will be a switch in the parameter setting. As a result, the pattern of children's early scope errors in different languages is attributed to the default settings of the scope parameters that happen to not match the target language, but are perfectly acceptable in many other languages of the world. According to the nativist theory, these patterns of errors conform to the continuity hypothesis, namely that children's non-adult like linguistic behavior will consist of constructions that are attested in other human languages [@crain1991language].
<!--
Let me point out a problem with the parametric scope claim and the innate scope claim here. The nativist literature is not clear on whether one scope relation is more salient than the other in such languages or that only one scope relation is available. Given the modularity matching model, the claim seems to be that given the syntactic parameters of the language, only one logical form is available for *and* and *or* under negation. However, such an account will face empirical issues. In the following English example, the salient reading of *or* is one where it scopes above negation (contrary to the generalization in innateness of scope) :

(15)

A: Did you know that Mike Huckabee has been running for every presidential election since 2000? 

B: No, he missed one. He didn't run in 2008 or 2012. I'm not sure which.

Below is a naturally-occurring example of Mandarin where disjunction scopes under negation, again contrary to the generalization presented in the nativist literature for Mandarin.

(16) 

liang	xueya			qian,	bu		yao	chi	zaocan		huo	fu	yao

measure	blood-pressure	before,	NEG	will 	eat	breakfast 	or	take	medicine

"Before measuring blood pressure, do not eat breakfast or take medicine."

And finally in this example from Persian, both scope relations are available and are disambiguated by the context. 

(17)  

Ali ya Reza ro davat na-kon

Ali or Reza OM invite NEG-do

1. "Don't invite Ali and don't invite Reza" 

2. "Either don't invite Ali or don't invite Reza"

It is not clear what the disjunction scope parameter setting should be for the Persian speaker. One way to remedy this is to add a third value to the parameters that makes both scope relations possible. Therefore, the correct setting for English, Mandarin, and Persian would be this third value. However, adding a third value to each parameter has consequences for the the nativist theory including on how to choose the default parameter. Currently, the choice of the default parameter is based on the semantic subset principle. Given a sentence with more than one interpretation such that the interpretations form a subset-superset relationship, learners are innately guided to initially choose the representation that is true in the smallest set of circumstances. [@crain1994learning]

The hypothesis above is a semantic version of the more general "subset principle" for language learning [@berwick1985acquisition, @wexler1987parameters]. The subset principle suggests that "the learner must guess the smallest possible language compatible with the input at each stage of the learning procedure" [@clark1993computational]. The subset principle aids the learner in situations where no negative evidence is present. However, the claim that children's input does not contain negative evidence has been a major source of contention in children's acquisition of syntax (see @marcus1993negative, @chouinard2003adult) and it is even more dubious whether it can extend to semantic acquisition. The main reason is that even those arguing for the syntactic version of the claim, acknowledge that adults do correct children on the content and semantics of their utterances. Therefore, the claim that there is no negative evidence with respect to the meaning of logical words and subsequently the semantic subset hypothesis need much more empirical support. Logical nativism also argues that children do not have sufficient evidence from experience to learn the meaning of logical expressions by observing how adult speakers use them. For example, *or* is rare in children's input data and it is more consistent with an exclusive meaning in its most frequent use.
-->
Finally, the hypothesis that logical meaning is innate along with the claim that young children fail at adult-like computation of scalar implicatures leads to the formulation of the logical stage hypothesis. According to this hypothesis, children's acquisition of meaning for certain logical operators follow two stages. First, the logical stage in which they assign the basic logical meaning to the logical words and do not compute standard implicatures associated with them. Second, the pragmatic (adult-like) stage in which the basic semantics of these words is enriched with pragmatic implicatures.

The logical stage hypothesis along with the innateness of logical meaning result in the prediction that children's initial interpretation of *or* should be inclusive and that only later when they reach the pragmatic stage they are capable of deriving the exclusive reading (Inclusive-First hypothesis). The prediction above is the opposite of the exclusive-first prediction made by the usage-based account of language acquisition.

### The Empirical Landscape {#GriceanEmpirical}

Almost all nativist studies use the Truth Value Judgment Task (TVJT) of @crain1998investigations. TVJT involves a storyteller, a story, and a puppet. One experimenter is in charge of narrating the story and the other experimenter is in charge of the puppet. The story creates the context for the evaluation of the target sentence and then the puppet utters the target sentence either as a description of what happened in the story (Description Mode), or as a prediction of what will happen next (Prediction Mode). In Prediction Mode, the story continues so that the child can see whether the prediction of the puppet was realized or not. Then the puppet repeats the prediction and either the puppet itself or the storyteller asks the child whether the puppet was right. Children can provide their judgments either by saying "Yes" or "No" (or other equivalent utterances). Sometimes children are asked to reward the puppet if the puppet was right. When children say that the puppet is wrong, they are asked to explain why.

An advantage of TVJT is that it allows for an explicit truth value judgement from children rather than relying on implicit measures or behaviors. However, as @crain1998investigations acknowledge, children tend to accept utterances when they are confused or uncertain as well. As a result, their rejections and explanations about their rejections are much more informative than their acceptances of the target sentence. Since inclusive interpretations involve more positive responses than exclusive or conjunctive responses, it is possible that TVJT has a slight tendency to overestimate inclusive interpretations as well. This methodological issue about TVJT may have been neglected in a lot of later investigations of disjunction words where children's acceptance of *or* when both disjuncts were true was argued as a sign of the inclusive meaning for *or*. However, it may be the case that children accept such cases due to the uncertainty they have with respect to the judgment.

There have been numerous Gricean/nativist studies of disjunction and a detailed discussion of each study is beyond the scope of this chapter. Therefore, in what follows, I first discuss some of the main findings and important topics in this literature and finally provide a brief summary of the studies I have surveyed in Table \@ref(tab:nativtable). Fortunately, a comprehensive discussion of the nativist theory and empirical findings is already available in @crain2012emergence.

The Griean and nativist investigations into children's interpretation of *or* started with @chierchia1998some. They argued that in order to truly understand children's semantic knowledge of *or*, we need to test it in contexts where it is not accompanied by exclusivity implicatures. This reasoning is adopted by the majority of nativist studies since then and as a result, in most of these studies the disjunction word is embedded under some implicature-cancelling operator such as negation or the restriction of a universal quantifier. However, such environments sometimes make the interpretaton of the connective *or* similar to *and*. For example, @notley2012children test the interpretation of *or* in the scope of *before*. However, a sentence such as "The dog reached the finish line before the turtle or the bunny" receives the same interpretation as its counterpart with *and*. The same is true for the restriction of a universal quantifier such as *every*: "Every boy or/and girl finished the task." Negation has a similar problem given that often both can be interpreted as "neither": "He did not eat the carrot and/or the pepper." (emphasizing *and* often avoids the "neither" reading in negative sentences.) As a result, such linguistic environments may mistakenly group responses from children that distinguish *and* from *or* and those who do not. Many studies also did not use a statement with *and* as a control.
<!--
@chierchia1998some argued that scalar implicatures are not generated when the speaker has uncertainty with respect to the outcome. So they tested children in two conditions: one in which the sentence with *or* was with a past tense verb and as a description, and another where the sentence had the modal *will* and was a prediction. They reported that when both disjuncts were true, children rejected the test sentence as a description but accepted it as a prediction. The conclusion was that contrary to the reports in the literature on children's logical reasoning, children understand the semantics of *or* as inclusive and not exclusive. The culprit behind the previous findings was the exclusivity implicature that the experiments did not control for. Since @chierchia1998some did not report the children's age range, it is hard to compare the results with the current investigations of scalar implicatures. -->

@su2014acquisition investigated the interpretation of disjunction in conditional sentences in Mandarin speaking participants. A great advantage of this study is that it had both adult controls as well as a control task with conjunction. Here I discuss two studies reported by @su2014acquisition. The first study tested children and adults interpretation of the Mandarin disjunction word *huozhe* in conditional constructions with *ruguo*. 32 children (2;6-5m M=3;9) and 28 adults were tested on sentences such as "if Mickey Mouse conjures up a rabbit or a bear, then he can get a reward" as well as "if the elephant jumped over the big stone, then he got a pear or a strawberry." There were 8 trials for each sentence. In half of them both disjuncts were true (e.g. Mickey mouse conjured up a rabbit as well as a bear), and in another half only one was true. When *huozhe* was in the antecedent of the conditional (e.g. if Mickey Mouse conjures up a rabbit or a bear, ...), children accepted the sentence (i.e. rewarded the puppet) when either one or both disjuncts were true. Adults showed a similar acceptance pattern. When *huozhe* was in the consequent of the conditional (e.g. ... then he got a pear or a strawberry), children accepted the sentences either when one disjunct or both were true. Adults, on the other hand, accepted the sentences when only one of the disjuncts was true. The results suggested that children interpret *huozhe* as inclusive disjunction in the antecedent as well as the consequent of conditionals. Adults, on the other hand, intepreted *huozhe* as inclusive disjunction in the antecedent and exclusive disjunction in the consequent of the conditional.

In a second task, @su2014acquisition compared the interpretation of conjunction and disjunction in Mandarin conditionals like "If a caterpillar picks a green leaf or/and a red flower, then we will get a painting" as well as "If the swordfish walks out of the maze, then he will get a butterfly or a crown." 29 Mandarin-speaking children (3;11-6;6, M=4;11) and 15 adults were tested. The results showed that children differentiated between *and* and *or* both in the antecedent and the consequent of the conditional construction. Based on these findings, @su2014acquisition argued that children differentiate between the meanings of conjunction and disjunction, and that the earliest meaning they assign to disjunction words is inclusive. She contended that "children's adherence to inclusive-or in both the two conditional clauses runs counter to the assumption on the usage-based account, according to which children's initial knowledge of disjunction is restricted to the nonlogical meaning of exclusive-or."

It is important to point out that some recent studies adopt Gricean assumptions, yet do not necessarily assume nativism. In the remainder of this section I discuss some of these studies. @hochstein2014ignorance tested 22 English-speaking four-year olds (M=4;4, 4;0-4;11) and 21 five-year olds (M=5;4, 5;0-5;11). They tested each group on two inferences/tasks: ignorance implicature and exclusivity implicature. In each task, participants watched a scene, the experimenter presented a description, and s/he asked participants to determine which of two characters uttered the sentence. In the ignorance implicature task, there were two characters, one blindfolded and one not. There were two objects on the table and in the critical trials an animal took one or both objects. The experimenter quoted one of the characters, for example: "someone said the bear took a cup or a plate." Then the experimenter asked: "Who do you think said that?" The study found that five-year olds successfully identified the disjunctive statement with the character that was blindfolded, probably reasoning that the character who could see the scene could have uttered a more infomrative sentence. This was not the case for four year olds. 

In the second task, both characters saw the scene, but one was introduced as a smart puppet and one as a silly puppet. Experimenters placed two animals on the scene, each having some fruits. In a control condition each animal had 3 apples and the experimenter reported that: "someone said each animal has two apples." The study showed that children picked the silly puppet as the speaker. In the exclusivity condition, each animal had an apple and a strawberry. The experimenter reported that: "someone said each animal has an apple or a strawberry". In this condition, children (both four- and five-year olds) were more likely to pick the smart puppet as the speaker. @hochstein2014ignorance concluded that children did not find it infelicitous when a disjunction had both disjuncts true, which suggests an inclusive interpretation. Unfortunately the study did not use adult controls so it is hard to know if the rate of exclusive interpreations in this study is significantly lower than what adults would have had.

<!-- resurgence of conjunctive readings -->

More recently, some studies have revived the earlier findings that preschool children can interpret disjunction as conjunction. @Singh2016 tested 56 English-speaking children (M=4;11, 3;9-6;4) and 26 adults in a TVJT task. The experiment had four pictures: a boy holding a banana, a boy holding an apple and a banana, three boys holding either an apple or a banana, and three boys holding both apples and banans. In each trial, participants saw one of the pictures and a puppet described the pictures with four possible utterances: "The/every boy is holding an apple or/and a banana." Participants were asked: "Was [the puppet] right or wrong about this picture?" They found that children were more likely to say the puppet was right when both disjuncts were true than when only one was. They concluded that "many preschool children - the majority in [the study's] sample - understand disjunctive sentences ... as if they were conjunctions." 

Since previous nativist studies suggested that children understood the meaning of *or* as inclusive disjunction, @Singh2016 proposed to explain both sets of findings using @fox2007free's proposal for deriving free choice inferences. The explanation goes like this. Children understand the meaning of *or* as inclusive disjunction. However, some children perform the typical inference on a free-choice sentence (e.g. The boy may have an apple or a banana) on non-free-choice sentences too (e.g. the boy is holding an apple or a banana). After hearing the non-free-choice sentence, they generate two alternatives: the boy is only holding an apple, the boy is only holding a banana. Then they negate these two alternatives: the boy is not only holding an apple, the boy is not only holding a banana. The combination of these two negated alternatives and the inclusive interpretation of "the boy is holding an apple or a banana" becomes something like this: "the boy is holding an apple, a banana, or both. He is not only holding an apple, and he is not only holding a banana." This compound statement is equivalent to "the boy is holding an apple AND a banana."

It is important to note that @Singh2016 tested the participants' understanding of *or* in another way too. They asked them "Was [the puppet] right or wrong about this picture?" It seems that the participants correctly interpreted this disjunction as exclusive and did not think the experimenter wanted their assessment on something that can be both "right and wrong". In other words, the conjunctive interpretation was not present for the question used by the experimenter, otherwise there could have been a lot of confusion with respect to the goal of the task. The fact that children showed different interpretations of *or* in the question sentence and in the puppet statements suggests that they are sensitive to the context of use.

@tieu2016 also found evidence for conjunctive interpretations of disjunciton in preschool children. They tested 28 French-speaking children (3;07-6;06, M=4;05) and 18 Japanese-speaking children (4;07-6;06, M=5;05) as well as 20 French-speaking and 21 Japanese-speaking adults. They used the "prediction mode" of the Truth Value Judgment Task, in which the puppet provides a prediction or guess, an event happens, and participants are asked if the prediction was right. For example, there was a chicken on the screen, next to a toy bus and a toy plane. The puppet appeared on the screen and predicted that "the chicken pushed the bus or the plane." Then the chicken either pushed one or both of the objects. Participants stamped on a happy or sad face to show whether the puppet's guess was right or wrong. Similar to @Singh2016, they reported that unlike adults, children were more likely to consider the disjunctive guess right when both disjuncts were true, rather than only one. They concluded that children - the majority of them in their sample - interpreted disjunction as conjunction. 

However, a recent replication of @tieu2016 by @skordosEtal2018 suggests that the conjunctive interpretations were most likely due to aspects of the experiment design. They tested 126 preschoolers in three conditions: replication (N=43, 4;0-5;9, M=5;0), modified script (N=41, 4;0-5;10, M=5;0), and three-alternatives (N=42, 4;0-5;11, M=5;0). The first condition was a direct replication of @tieu2016. The second condition, modified script, removed some experimenter comments right after the puppet's guess that could potentially confuse children. The comments were: "Look! The chicken pushed that! She didn't want to break that one. So she didn't touch it. So was [the puppet] right?" The third condition, three-alternatives, was similar to modified-script but provided three objects; for example a plane, a bus, and a bicycle. The reasoning was that if there are only two alternatives, a disjunction is trivially true, and consequently children may consider that unacceptable. The results replicated @tieu2016's findings in the replication condition, but showed that conjunctive interpretations of disjunction disappered almost completely in the third condition with three-alternatives. @skordosEtal2018 concluded that children's conjunctive interpretations are most likely due to non-linguistic strategies applied when they are uncertain about aspects of the experimental task. This conclusion is similar to that of early studies on conjunctive interpretations of disjunction in the 70s and 80s.  

|Study | Age | $N$ | Language | Environment | Interpretation |
|-------------------|:---:|:-:|:------:|---------------------|:--------:|
|@chierchia1998some | Not Reported | 23 + 10 | English + Italian | Past Declarative | $\oplus$|
| | |  |  | Future (*will*) | $\lor$|
|@gualmini2000inclusion | 4;1-6;1 (M=4;11) | 16 | English | *can* | $\lor$|
|@gualmini2000 | 3;2-5;9 (M=4;8) | 14 | English | *if* (antecedent) | $\lor$|
|@crain2000acquisition | 3;5-6;1 (M=4;1) | 13 | English | *will not* | $\lor$|
|@chierchia2001acquisition | 3;7-6;3 (M=4;11) | 15 | English | *every* restriction | $\lor$|
| | 3;5-6;2 (M=5;2) | 15 | English | *every* nuclear scope | $\oplus$|
|@gualminicrain2002 | 3;10-5;10 (M=4;7) | 30 | English | *none* nuclear scope | $\lor$|
|@chierchia2004semantic | 5;1-6;0 (M=5;5) | 9 | Italian | Future Tense | $\lor$|
|@goro2004acquisition | 3;7-6;3 (M=5;3) | 30 | Japanese | Negation (*nakat*) | $\lor$|
|@notley2012children | 3;4-5;1 (M=4;4) | 24 | English | *before* | $\lor$|
| | 4;6-5;4 (M=4;7) | 20 | Mandarin | *before* | $\lor$|
|@notley2012notevery | 4;2-5;2 (M=4;8) | 17 | English | *not every* restriction | $\lor$|
| | |  |  | *not every* nuclear scope | $\lor$ |
|@su2013disjunction | 3;11-5;11 (M=4;10) | 31 | Mandarin | *mei* (every restriction) | $\lor$|
| | | | | *mei* (every nuclear scope) | $\oplus$|
|(DO construction) | 4;1-5;8 (M=4;11) | 34 | Mandarin | *mei* (every restriction) | $\lor$|
|	| | | | *mei* (every nuclear scope) | $\oplus$|
|@su2014acquisition | 2;6-5;0 (M=3;9) | 32 | Mandarin | *ruguo* (if antecedent) | $\lor$|
| | | | | *ruguo* (if consequent) | $\lor$|
| | 3;11-5;11, (M=4;11) | 23 | Mandarin | *ruguo* (if consequent) | $\lor$|
| | | | | *ruguo* (if consequent) | $\lor$|
|@hochstein2014ignorance| 4;0-5;11 | 43 | English | *each* (nuclear scope) |$\lor$|
|@Singh2016 | 3;9-6;4 (M=4;11) | 56 | English | Present Declarative | $\land$, $\lor$, $\oplus$|
| | | | | *every* (nuclear scope) |
|@tieu2016 | 3;7-6;6 (M=4;5) | 28 | French | Past Declarative | $\land$, $\lor$, $\oplus$|
| | 4;7-6;6 (M=5;5) | 18 | Japanese | Past Declarative | |
| @gecckin2018children | 4;1-5;8 (M=4;07) | 24 | German | Negative Past | $\lor$ |
| | 4;1-5;11 (M=4;7) | 26 | Turkish | Negative Past | |
Table: (#tab:nativtable) The summary of studies on disjunction words in the nativist or Gricean accounts.

## Conclusion

Previous studies highlight the importance of linguistic context and task demands in preschool children's interpretation of disjunction. Early studies such as @johansson1975preschool suggest that in commands or imperative sentences, children are more likely to interpret a disjunction as exclusive. That is, they comply with the command by just making one of the disjuncts true. However, other studies show that in declarative sentences, disjunction often receives an inclusive interpretion. That is, children judge a sentence "right" when both disjuncts are true, as well as when only one is true. Conjunctive interpretations may appear with declarative sentences too where children respond to statements with *or* in a manner that is similar to statements with *and*. They may accept the disjunctive statement when both disjuncts are true and reject it when only one is true. However, such responses can also be present in adults and seem to be caused by aspects of the experimental design. In tasks with relatively high cognitive demands or high levels of uncertainty with respect to the goal of the task, participants may apply non-linguistic strategies that disregard the meaning of the connective and simulate a conjunctive interpretation.

Therefore, when studying children's interpretation of disjunciton, it is important to control for the following factors: complexity of the linguistic stimuli, complexity of the task, ignorance of the speaker, interpretation of the conjunction word (e.g. *and*) in the same task, and finally interpretation of adults in the same task. Previous studies have sometimes used complex linguistic stimuli, relatively complex design, had the speaker utter the disjunction when the truth of the propositions were known to the speaker, did not use the conjunction word in a control trial, or did not use adults as control participants. In the next chapter, I present an experiment that addresses these issues.
