# Conclusion {#conclusion}

This dissertation engaged with two questions at the intersection of meaning and development. First, how do children learn the meaning of function words? Second, how do children learn the meaning of a disjunction word like *or* in English? The first question is broad and can be answered by investigating children's acquisition of different types of function words across languages. That is what the second question is about, focusing on the word *or* in English. In addressing the second question, my goal was to engage with the broader question of function word acquisition in children and build on previous research in this area. In this section, I first summarize how this dissertation addressed the narrower question of learning disjunction in English. Then I show how the findings can shed light on the broader issue of learning function words.

I started this dissertation with a summary of the research in semantics and pragmatics on disjunction. In language, disjunction can give rise to a number of implications. These implications include truth-functional ones such as inclusivity, exclusivity, and conjunctivity, as well as non-truth-functional ones like ignorance, and indifference. On the face of it, what a disjunction implies may seem arbitrary. Since @grice1989studies, however, decades of research have provided mounting evidence that the implications of a disjunction arise systematically through its interaction with other linguistic and sociopragmatic factors that shape the overall interpretation of an utterance. Chapter \@ref(sempragLit) discussed a non-exhaustive list of these factors, including the intonation of the disjunction, the semantic relation of the disjuncts themselves, the linguistic environment of the disjunction, as well as the communicative intention of the speaker. I argued that the interpretive factors discovered and discussed in theoretical semantics and pragmatics inform research in child language acquisition by providing a list of cues that may help children interpret a disjunction and learn the meaning of *or*.  

How often do children hear examples of *or*? Chapter \@ref(corpus) used a large body of child-directed speech to address this questions. It found that compared to *and*, *or* is relatively rare in child-directed speech. Per one thousand words, parents produced about 15 instances of *and* and only 1.5 instances of *or*. The study also found that on average, children produced *or* less often and later than *and*. Per thousand words, children produced about 15 instances of *and* but only 0.5 instances of *or*. Children started producing *and* between 1;0 and 1;6 years of age, but began to produce *or* only at 1;6 to 2;6 years. Furthermore, children reached their parents' rate of *and*-production around age 3, but did not reach their parents' rate of *or* production in the first six years of their lives. @morris2008logically had suggested that this developmental asymmetry between *and* and *or* was due to the differences in the frequency and usage of these connectives in child-directed speech. Chapter \@ref(corpus) provided another possible factor, namely the asymmetries in the social and conversational roles of parents and children. Parents and children do not communicate the same types of messages to each other. For example, it is not surprising to hear a parent say "go to your room" to a child. However, a child saying the same phrase to a parent is surprising and unexpected! 

My large scale corpus study found that parents ask more questions of children than children do of parents. In addition, the disjunction word *or* is more likely to occur in the context of questions than of declaratives. Therefore, parents may be producing more instances of *or*, simply because they ask more questions. When I compared the production of *or* in declaratives and questions, I saw that children were closer to the parents' rate of *or* in declaratives. This finding suggests that the asymmetry between *and* and *or* may be due at least in part to the differences in speech acts produced by parents and children, and not necessarily to added difficulty for the disjunction word *or*. More generally, since the presence or absence of a function word depends on the overall communicative function of the utterance, it is important for production studies to control for the types of speech acts produced. Children may not produce a function word at the same rate as their parents simply because they do not produce the types of speech acts where that function word is typically used. Not reaching the parents' rate of production, therefore, does not necessarily imply incomplete acquisition. The large scale corpus study of Chapter \@ref(corpus) showed that on average, children start producing the connectives *and* and *or* around 1 to 2 years of age, and continue until they reach a relatively steady rate of production around age 4. 

The findings of the large scale corpus study are in line with comprehension studies that suggest children can interpret both connectives at the age of 4 years. Several studies in the past decade have shown that at age 4, children can interpret *or* as inclusive disjunction [@crain2012emergence]. However, @morris2008logically reported that the vast majority of examples children hear, and in fact produce, receive an exclusive interpretation. How can we reconcile these two findings? How can children learn an inclusive interpretation for *or* if they rarely hear it? I referred to this as the puzzle of learning disjunction. To answer this question, Chapter \@ref(corpus) also provided an annotation study. Examples of *or* were annotated for their interpretations, as well as several other features such as intonation, the semantic relation of the disjuncts, and their communicative functions. This study replicated the finding of @morris2008logically: exclusive interpretations of *or* are more common than the inclusive ones in child-directed speech. However, the study also found that exclusive interpretations are systematically accompanied by certain cues, most notably, a rise-fall intonation or the presence of inconsistent disjuncts like "stay or go". When these cues were absent, *or* received an inclusive interpretation. 

From the findings of the annotation study, I derived a learning account that addressed the puzzle of learning disjunction. I referred to this account as the cue-based context-dependent acquisition of *or*. Previous literature on disjunction seem to assume that *or* is mapped to its most likely interpretation as observed by the learner. I called this the default account. @morris2008logically found exclusive disjunction to be the most common interpretation of *or* in child-directed speech, and proposed that children initially learn its meaning as exclusive. To support this, he showed that *or* is also exclusive in children's early productions. As mentioned before, comprehension studies found that preschool children (in the same age range) were more likely to interpret a disjunction as inclusive. How can this be? 

An important property of the default account is that it disregards the context of *or* when learning its meaning. In Chapter \@ref(modeling) I argued that such a context-independent mapping of *or* to its meaning is the source of the learning puzzle for disjunction. I suggested that a small change to the default account could solve this problem. Instead of mapping the word *or* directly, independent of context, to its interpretations, disjunction as a whole can be mapped along with any available contextual cues to an interpretation. This way, it is not *or* that is interpreted as exclusive, but rather *or* with a rise-fall intonation or with inconsistent disjuncts. In the absence of these cues, the most likely interpretation of a disjunction would be inclusive. When contextual cues are used to learn the interpretation of a disjunction, the learner can know which contexts favor an inclusive inclusive, and which an exclusive one. The modeling experiments of  Chapter \@ref(modeling) showed that such a cue-based context-dependent learning is successful in classifying examples of disjunction as inclusive versus exclusive. Crucially, inclusive interpretations were more likely in the context of declarative sentences with flat intonation and consistent disjuncts. These are the types of sentences that comprehension studies used to test children's knowledge of disjunction. This account, therefore, shows how children can learn an inclusive interpretation for disjunction from an input dominated by exclusive examples. 

In Chapter \@ref(devoLit), I provided a review of the developmental research on children's comprehension of disjunction. Early studies in the 1970s and 1980s suggested that children and even adults struggle with understanding a disjunction. They either interpret it as exclusive or conjunctive. However, further investigations suggested that conjunctive interpretations might be attributable to non-linguistic strategies deployed when the task is too demanding or perhaps confusing to participants. More recent studies within a Gricean framework have suggested that children interpret *or* as inclusive disjunction. However, it is hard to compare the results between recent findings and earlier ones because they differ along several dimensions. The review concluded that future studies should control for the complexity of the linguistic stimuli, the complexity of the task, the ignorance of the speaker, the interpretation of the conjunction word (e.g. *and*) in the same task, and finally the interpretation of adults in the same task. Chapter \@ref(comprehension) presented a set of experiments with children and adults that controlled for these factors.

In Chapter \@ref(comprehension), I tested adults and children's interpretation of conjunction and disjunction in English existential constructions in the context of a guessing game. In each trial, participants saw a card and a blindfolded character guessed what animals were on the card. For example, the character guessed "there is a cat or a dog" when there was a cat and a dog on the card. Participants were asked to judge if the guess was right. In one set of experiments children and adults provided binary responses of "right" and "wrong"; in another set, ternary responses of "right", "a little right", and "wrong". The binary results found no statistically significant difference between children's and adults' truth judgments. The results of the ternary task found only that children were more accepting of disjunction when both disjuncts were true. For example, when the character guessed "cat or dog" and both animals were on the card, children were more likely to say "right" and adults were more likely to say "a little right". Overall, both adults and children provided inclusive interpretations for disjunction in the existential sentences of the guessing game. The results are compatible with the prediction of the cue-based context-dependent account presented in Chapter \@ref(modeling).

The studies in Chapter \@ref(comprehension) also investigated children's spontaneous feedback to the guesser, a puppet, in the experimental setting. Children's feedback was divided into three categories: judgments (yes/no), descriptions (naming the animals), corrections (focusing what the puppet should have said). The results showed that children provided corrections when the guess was either false or infelicitous. Most notably, in trials where a disjunction like "cat or dog" was used and both animals were on the card, children judged the guess as "right" but provided corrections to the puppet. For example, they said "cat and dog", emphasizing the word *and*. Some also mentioned the word *both*. The analysis of children's linguistic feedback suggested that truth value judgments may underestimate children's linguistic competence. I ended this chapter with the discussion of the methodological challenges in assessing and measuring children's semantic and pragmatic knowledge. 

What does the acquisition of *or* teach us about function words in general? First, the case of *or* in English shows that theories of word learning should not ignore the context of form-meaning mapping. Previous approaches to the acquisition of the lexicon often rely on isolating a word form, isolating a meaning, and mapping the form to the meaning. The case of *or* shows that "word form" can extend beyond the word to encompass the intonational contour on the whole disjunction. It also shows that "meaning" can extend to include the semantic relations of the disjuncts themselves, for example, whether they are consistent or inconsistent with each other. In order to successfully learn the interpretation of *or*, the learner must attend to the cues available in the context of the word. 

The second lesson is methodological. The case of *or* shows that the development of function words is better understood if evidence is gathered from three sources: child-directed speech, children's comprehension, and children's production. In the case of *or*, each source provides invaluable and complementary insight about how children learn the meaning of *or*. Each source individually provides information that may miss crucial aspects of the full development. It is only when all three are taken into account together and reconciled, that a coherent developmental account emerges. Ideally, we construct formal models that use child-directed speech to predict children's comprehension and production at a specific age. The aim of this dissertation was to take a first step in this direction. My hope is that future work on similar functions words will extend, improve, and standardize this methodology to result in a general theory of function word acquisition.
