---
title: 'Learning Disjunction'
author: 'Masoud Jasbi'
date: 'May 2018'
advisor: 'Eve V. Clark'
firstreader: 'Christopher G. Potts'
secondreader: 'Michael C. Frank'
thirdreader: 'Ellen M. Markman'
department: 'Linguistics'
institution: 'Stanford University'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  thesisdown::thesis_pdf: default
#  thesisdown::thesis_gitbook: default
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
acknowledgements: |
 `r if(knitr:::is_latex_output()) paste(readLines("00-acknowledge.Rmd"), collapse = '\n  ')`

dedication: |
  To my parents, Abbas Jasbi and Tahereh Haj-Ebrahimi, who taught me the meaning of *life*.
#preface: |
#  This is an example of a thesis setup to use the reed thesis document class
bibliography: bib/dissertation_biblio.bib
csl: csl/apa.csl
lot: true
lof: true
#space_between_paragraphs: true
#header-includes:
#- \usepackage{tikz}
---

```{r include_packages, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(thesisdown)
```

# Introduction

In the literature on word learning, the story goes that one day, a linguist with great mastery of phonetics and phonology, heard of a people with an unknown language. She immediately packed her bags and traveled to learn about this new language. When she arrived, she saw a man walking down the road. Suddenly a rabbit scurried by. The man saw the rabbit and said "gavagai". The linguist immediately pulled out her notebook. As an excellent phonetician with trained ears for detecting linguistic sounds, she wrote down the phonetic transcription of what she heard with great confidence. It was only when she tried to write the meaning that doubt and uncertainty seeped in. "Does *gavagai* mean rabbit?", she whispered quietly. As a good scientist, she could see that her observation was compatible with a large number of hypotheses for the meaning of *gavagai*: "white-thing", "furry thing", "animal", "fast", "what was that?", "oh gosh!", "rabbit-on-the-road", and even "undetached rabbit parts"! She shook her head and let out a sigh. She had encountered "referential uncertainty" [@quine1960word, Ch. 2, pp. 27].

Unlike what most of us think, the story did not end there [@quine1960word, Ch. 2, pp. 52]. The linguist continued with her observations and soon she learned the meaning of *gavagai* as well as many other words, mostly nouns, adjectives, and verbs. But soon she encountered a new challenge. One day when she was walking down the same road with the same man, she noticed some movement in the nearby bushes. The man pointed to the bushes and said: "tonomi yok gavagai". She knew that *gavagai* meant "rabbit". She also knew that *tonomi* was another animal. But she had never heard the word *yok* before. What did *yok* mean? Maybe the man saw an animal and was not sure whether it was a gavagai **or** a tonomi. However, the man did not sound uncertain. What if he was trying to say that the animal was a gavagai **and not** a tonomi? Maybe he saw two animals and wanted to let her know that there was a gavagai **and** a tonomi in the bushes. It was also possible that by that time, the man knew she was trying to learn their language and wanted to let her know that *gavagai* and *tonomi* are terms that apply to the same animal; something like: "this is called a gavagai **or** a tonomi". The linguist in our story sighed again. Even though she knew the meaning of words for things and actions, she needed to know the meaning of words that put them together to convey larger concepts. Legend has it that she did not go home until she discovered the meaning of all such "function words" in the language.

## Word Learning

Learning the meaning of a word is often construed as mapping a linguistic form such as *gavagai* to a concept/meaning such as "rabbit". This mapping process is described in three stages: First the learner isolates the word form; then s/he isolates a meaning from a set of possible meanings; and finally s/he maps (or associates) the isolated word to the isolated meaning [@clark1993lexicon]. A fundamental question in the acquisition of meaning concerns the second step of mapping: how do children select the right meaning from a set of candidate meanings? @quine1960word's thought experiment with the linguist and the new language showed that this is not a trivial task. In any given context, a word is compatible with many possible meanings. The problem of selecting the right meaning for a given word is called the "mapping problem" or the "gavagai problem".

Solutions to the mapping problem often place constraints on either the hypothesis space or the structure of the lexicon to make word learning tractable [@clark1993lexicon]. For example, the taxonomic constraint [@markman1984children] proposes that children generate semantic hypotheses for nouns that denote a set of taxonomically related entities and do not hypothesize meanings that capture sets of entities with thematic relations. For example, given the word *gavagai*, children hypothesize the meaning "rabbit" which denotes the set of rabbits (taxonomically related) but not "rabbit and carrot" (thematically related). Therefore, the taxonomic constraint limits the space of hypotheses that the learner entertains. On the other hand, the mutual exclusivity constraint [@markman1988children] as well as the pragmatic principle of contrast [@clark1987principle] limit the structure of the lexicon such that two words are not mapped into the same meaning. This constraint on the lexicon makes the word learning task easier by removing hypotheses that are already associated with learned words.

Another solution to the mapping problem is to propose cues that bias the learner towards one hypothesis rather than another. For example, socio-pragmatic cues such as pointing and joint-attention [@baldwin1993infants; @tomasello2003constructing; @clark2009first] direct the learner to bias one hypothesis over others. For example, given a rabbit and a cat, the speaker pointing to the rabbit and saying *gavagai* biases the learner to map the meaning of *gavagai* to "rabbit" rather than "cat". Learning models can also integrate cues and constraints to develop a learning account that uses multiple cues to home in on the target meaning of a word [@hollich2000breaking].

While there has been a large body of research on the set of cues and constraints that aid the acquisition of content word, function words have not received comparable attention. This dissertation takes a small step in advancing research on the acquisition of functions words by focusing on the challenging case of the disjunction word *or*. The case of *or* shows that function words, due to their special properties such as abstract and variable interpretations, will play an important role in shaping theories of word learning. In the next section I explain the scope of this dissertation within a program that aims at developing a cue-based acquisition of function words.

## Defining the Scope

The lexicon of a language can be divided into two classes: content words and function words. Content words consist of nouns (e.g. *cat*, *Bob*, *freedom*), verbs (e.g. *run*, *blink*, *imagine*), adjectives (e.g. *happy*, *red*, *fake*), and adverbs (e.g. *fast*, *quietly*, *quickly*). Function words include articles (e.g. *a*, *the*), quantifiers (e.g. *some*, *most*, *all*), prepositions (e.g. *in*, *on*, *at*), pronouns (e.g. *he*, *they*, *her*), auxiliary verbs (e.g. *did*, *can*, *am/is/are*), connectives (e.g. *or*, *if*, *because*), interrogatives (e.g. *who*, *what*, *when*) and more. Function words differ from content words in (at least) five crucial ways. First, function words are phonologically simpler than content words [@shi1996perceptual]. Second, even though content words vastly outnumber function words, function words are a lot more frequent. Third, while content words frequently admit new members, function words rarely do so. This is why content words are considered an open class in the lexicon while function words are called a closed-class. Fourth, the common intuition is that content words carry more meaning and the concepts they denote are more tangible. The meanings of function words, however, are subtle and abstract. Finally, function words appear in children's speech later than content words<!--citation-->.

Even though content words are more salient and commonly steal the spotlight in public discourse, the unique properties of function words make them a valuable resource to linguists and cognitive scientists. They are the essential nuts and bolts that combine smaller words and concepts to form large sentences and thoughts. They provide crucial information on the structure and inner workings of language. The crosslinguistic and psycholinguistic study of function words provides us with an exceptional window into the structure and building blocks of our minds.

Within function words, logical connectives *and*, *or*, *not*, *if*, have received considerable attention in the linguistic and psychological literature due to the foundational role that the concepts of conjunction, disjunction, negation, and implication play in logic and mathematics. In linguistics and philosophy, a large body of research has investigated the connections between the meanings of these words and their corresponding operators in formal logics. Similarly in psychology, there has been substantial research on children's development and adults comprehension of logical concepts and logical reasoning. This dissertation focuses on the acquisition of the disjunction word *or* by preschool children. It proposes a learning account for *or* (and its counterpart *and*), that can be expanded in the future to linguistic connectives in general such as *but*, *because*, *yet*, *so*, *after*, *before*, *although*, *however*, etc. 

## Why Disjunction?

The disjunction word *or* has been the lab rat of formal semantics and pragmatics. The main reason is that even though it seems to have a simple meaning, it gives rise to a variety of inferences that reveal the interaction of semantics and pragmatics. In fact, Paul Grice's original investigations that lead to the birth of formal pragmatics was partly motivated by resolving apparent discrepancies between the logical and linguistic accounts for the meaning of disjunction [@grice1989studies]. Since then, there has been a flood of research on the meaning of *or* and as a result, much more is known about the meaning and interpretation of *or* than perhaps any other function word. This makes *or* an ideal case for better understanding how the meaning of function words are learned by children. Furthermore, research on disjunction has lead to a developmental puzzle that I explain in the next section. 

## The Puzzle of Learning Disjunction

The word *or* has been a case study for linguistic semantics due to its apparent ambiguity between an inclusive and an exclusive interpretation. An inclusive disjunction such as "A $\vee$ B" is true when either A, B, or both are true. An exclusive disjunction such as "A $\oplus$ B" is true only when A or B is true, but not both. The linguistic connective *or* appears to be ambiguous between an inclusive interpretation like "A $\vee$ B" and an exclusive one like "A $\oplus$ B". For example, a waiter may ask if you would like something to eat or drink, not excluding the possibility that you would like both. This is an inclusive disjunction. However, the waiter may later ask if you would like to see the dessert menu or have the check, suggesting that you should choose one or the other, and not both. This is an exclusive disjunction.

Given the complexity involved in interpreting a disjunction, how can children learn it? A previous investigation has suggested that children rarely hear the word *or*; and when they do, they hear the exclusive interpretation. @morris2008logically investigated instances of *and* and *or* in parents' and children's speech using 240 transcripts in the CHILDES database [@macwhinney2000childes]. He found that compared to *and*, *or* is rare in child-directed speech. Furthermore, the majority of *or* examples children heard (75-80\%) and produced (90\%) had exclusive interpretations. Based on these findings, he concluded that children's early meaning for *or* is exclusive disjunction and that they learn the inclusive meaning in later stages of development (possibly at age 6 or 7).

Contrary to @morris2008logically's conclusion, a series of experimental studies found that children between the ages of 3 and 5 can interpret *or* as inclusive disjunction [@chierchia2001acquisition; @crain2012emergence; @jasbi2017]. Given @morris2008logically's finding that the majority of *or* examples children hear are exclusive, we face a puzzle: how can children learn to interpret *or* as inclusive if they rarely hear inclusive examples of *or*? @crain2012emergence considered it unlikely that children learn the meaning of *or* from the examples they hear in adult usage. Instead, he argued that children rely on an innate knowledge that the meaning of a disjunction word must be inclusive. In other words, upon hearing a connective word, children consider inclusive disjunction (A $\vee$ B) as a viable candidate for its meaning but not exclusive disjunction (A $\oplus$ B). This dissertation provides an alternative answer to the puzzle of learning disjunction. It suggests that children can learn when a disjunction must be interpreted as inclusive if they pay attention to the contextual cues that accompany exclusive uses.

## The Structure of the Dissertation

This dissertation consists of two main parts. Chapters \@ref(sempragLit)-\@ref(modeling) constitute the first part and Chapters \@ref(devoLit)-\@ref(comprehension) constitute the second part. The first part focuses on the interpretations of disjunction and how children can learn them from the language they hear. It proposes an account that uses multiple cues to learn the interpretation of a disjunction. The main methods used in this part are exploratory corpus studies and computational modeling. The second part discusses the comprehension of disjunction in children and adults, focusing on disjunction in declarative sentences. This part uses confirmatory experimental studies to test children's comprehension and compare them to adults. It shows that children's interpretations of *or* between the ages of 3 and 5 are in line with the predictions of the account presented in the first part. In what follows, I briefly describe the role of each chapter.

Chapter \@ref(sempragLit) provides an overview of the semantics and pragmatics of *or* in English. The main focus of the chapter is the empirical discoveries about the interpretations of disjunction in different linguistic and nonlinguistic contexts. The chapter shows that on the surface, a disjunction like "A or B" can be interpreted as inclusive (A or B, or both), exclusive (A or B, not both), or conjunctive (both A and B).  These interpretations are sometimes accompanied by ignorance implications (the speaker does not know which option is true) or indifference implications (the speaker does not care which option is true). The chapter discusses the factors that affect the interpretation of *or* in a given context. These factors include conversational principles, entailment environment, modality, disjunct semantics, intonation, syntax, metalinguistic speech acts, and some specific constructions such as embedded imperatives and unconditionals. The chapter argues that these factors can act as cues for the acquisition and interpretation of disjunction.

Chapter \@ref(corpus) presents two corpus studies. The first study presents a large-scale analysis of parents and children's productions of *and* and *or*. The results show that children start producing *and* between the first and the second years of their lives and reach their parents' rate of *and* production around their third birthday. For disjunction, children start producing *or* between two and three years of age and by the time they are four, they reach a constant rate of *or* production. This rate is slightly lower than that of their parents. The chapter discusses three factors that may contribute to children's lower rate of production: conceptual complexity, input frequency, and utterance type frequency. It argues that children's lower rate of production is at least partly due to utterance type frequency: parents ask more questions from children than children from parents. Since *or* is more common in questions, parents have more opportunities to use it than children. Overall, the findings suggest that children develop their understanding of disjunction between their second and fourth birthdays.

The second corpus study selected a subset of *and* and *or* in child-directed speech for five children between the ages of one and three. First, every instance of *or* in a question was annotated for the type of response it received from children. The results showed that around age 2, children start providing appropriate answers to questions with disjunction. Second, the study annotated utterances containing *and* and *or* for their interpretation (exclusive, inclusive, conjunctive), as well as five types of cues: intonation (flat, rising, rise-fall), utterance type (declarative, question, imperative), syntax (clausal vs. subclausal), consistency (inconsistent: "clean or dirty" - consistent: "clean or tidy"), and communicative function. The results confirmed previous findings that exclusive interpretations are more common in children's input than non-exclusive ones. However, the study also found that intonation and consistency play a large role in determining whether a disjunction is exclusive or not. If intonation was rise-fall, or the disjuncts were inconsistent, the disjunction was most likely exclusive; otherwise, inclusive. These results show that even though exclusive interpretations are more common in children's input, they correlate with certain contextual cues.

Based on the annotation study of Chapter \@ref(corpus), I introduce a learning account in Chapter \@ref(modeling) which uses contextual cues to learn the interpretations of disjunction. The basic idea behind this account is that *or* receives its interpretation as exclusive or inclusive based on the specific context of use. Given a set of contextual cues, *or* may receive an exclusive interpretation, while given another set of cues, it may be inclusive. Therefore, if the learner keeps track of contextual cues and how they correlate with the interpretation of a function word like *or*, she can learn multiple interpretations of a function word according to the context of use. I call this account cue-based context-dependent learning. 

I show that this account resolves the puzzle of learning disjunction. As a reminder, the puzzle asserted that children learn the inclusive interpretation of *or* despite the fact that most examples of *or* they hear are exclusive. I argue that this observation is only puzzling if we assume that function words like *or* should be mapped to their most frequent interpretation overall (e.g. exclusivity). However, the annotation study found that exclusive interpretations are common in certain contexts while inclusive ones are common in others. Therefore, if learners track contextual cues and learn the interpretation of a function word within a specific context of use, they can learn both the exclusive and inclusive interpretations of disjunction. To test this account more formally, I trained random decision forests [@ho1995random; @breiman2001random] on the annotation dataset developed in Chapter \@ref(corpus). While without using contextual cues, a disjunction was classified as exclusive, using contextual cues decision tree classifiers learned to classify instances of disjunction as exclusive and inclusive, depending on the context of use. Crucially, disjunctions in declarative sentences with a flat intonation and consistent alternatives (disjuncts) were found to be more likely to be inclusive. This is the context most frequently tested in comprehension studies on disjunction.

Chapter \@ref(devoLit) provides an overview of the developmental research on children's comprehension of disjunction. Early developmental research in the 70s and 80s suggested that children and even high school students struggled with correctly interpreting a disjunction. They reported that they interpreted it as conjunction and exclusive disjunction. Later research suggested that the conjunctive interpretations may be due to non-linguistic strategies that are deployed when the experimental tasks are demanding or confusing to participants. Recent studies in the past two decades within a Gricean framework of semantics and pragmatics have shown that children interpret *or* as inclusive disjunction, especially in declarative sentences. However, most previous studies did not control for one or more of the following factors: complexity of the linguistic stimuli, complexity of the task, ignorance of the speaker, interpretation of the conjunction word (e.g. *and*) in the same task, and finally interpretation of adults in the same task.

Controlling for the factors enumerated in Chapter \@ref(devoLit), Chapter \@ref(comprehension) presents three studies on adults' and children's comprehension of *or* in simple existential sentences ("there is A or B"). The first study tests adults comprehension of discussion using two and three-alternative forced-choice truth-value judgment tasks (2AFC and 3AFC TVJTs). The 2AFC task showed that adults interpret *and* as conjunction and *or* as inclusive disjunction. The 3AFC task showed that adults do not consider a disjunction completely felicitous when both disjuncts are true. The second study used a similar 3AFC task to test three-to-five year old children's comprehension of *and* and *or*. The study also analyzed and categorized children's open-ended spontaneous feedback in the task. Children's interpretations were similar to adults except in cases where both disjuncts were true. In such cases, children's forced choice responses showed no sign of infelicity while their spontaneous feedback showed such signs: children corrected the utterance with *or* and suggested that *and* should have been used instead. The third study used a two-alternative forced choice (2AFC) task and categorized children's open-ended feedback. The two-alternative forced choice task showed similar results to adults and the study replicated children's open-ended feedback in study 2: children provided corrections to the utterance when both disjuncts were true and offered the connective *and*. Overall the results suggested that three-to-five year old children's interpretations of disjunction may not differ substantially from those of adults. I review the findings of this dissertation and discuss the conclusions in Chapter \@ref(conclusion).
